### ISSUE TITLE
Error When compiling web part

### ISSUE THREAD

**Issue by NPrice99** [SPDoctor/SiteInfo#1]
Hi Bill

I tried your web part from last thursday but failed during compilation when including the SP-PNP-JS library.

Node version is v4.5.0 and npm version is v3.10.7.

Gulp ? says it is a problem with the sp-pnp-js v1.0.4 package.

148184 silly postinstall sp-pnp-js@1.0.4 C:\XXX\YYY\OneDrive\Documents\SPFx\Projects\SiteInfo-webpart\node_modules.staging\sp-pnp-js-9c34adce
148185 info lifecycle sp-pnp-js@1.0.4~postinstall: sp-pnp-js@1.0.4
148186 verbose lifecycle sp-pnp-js@1.0.4~postinstall: unsafe-perm in lifecycle true
148187 verbose lifecycle sp-pnp-js@1.0.4~postinstall: PATH: C:\XXX\YYY\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\XXX\YYY\OneDrive\Documents\SPFx\Projects\SiteInfo-webpart\node_modules\sp-pnp-js\node_modules.bin;C:\XXX\YYY\OneDrive\Documents\SPFx\Projects\SiteInfo-webpart\node_modules.bin;C:\XXX\YYY\Roaming\npm;C:\Program Files\nodejs\;C:\Python\;C:\Python\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files (x86)\Skype\Phone\;C:\XXX\YYY\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\XXX\YYY\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\XXX\YYY\AppData\Roaming\npm
148188 verbose lifecycle sp-pnp-js@1.0.4~postinstall: CWD: C:\XXX\YYY\OneDrive\Documents\SPFx\Projects\SiteInfo-webpart\node_modules\sp-pnp-js
148189 silly lifecycle sp-pnp-js@1.0.4~postinstall: Args: [ '/d /s /c', 'typings install' ]
148190 silly lifecycle sp-pnp-js@1.0.4~postinstall: Returned: code: 1  signal: null
148191 info lifecycle sp-pnp-js@1.0.4~postinstall: Failed to exec postinstall script
148192 verbose unlock done using C:\XXX\YYY\AppData\Roaming\npm-cache_locks\staging-f92886aaf346cfe3.lock for C:\XXX\YYY\OneDrive\Documents\SPFx\Projects\SiteInfo-webpart\node_modules.staging
148193 silly rollbackFailedOptional Starting
148194 silly rollbackFailedOptional Finishing
148195 silly runTopLevelLifecycles Finishing
148196 silly install printInstalled
148197 warn optional Skipping failed optional dependency /chokidar/fsevents:
148198 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
148199 warn globalize-compiler@0.2.0 requires a peer of cldr-data@>=25 but none was installed.
148200 warn globalize@1.1.1 requires a peer of cldr-data@>=25 but none was installed.
148201 warn cldrjs@0.4.4 requires a peer of cldr-data@>=25 but none was installed.
148202 verbose stack Error: sp-pnp-js@1.0.4 postinstall: `typings install`
148202 verbose stack Exit status 1
148202 verbose stack     at EventEmitter.<anonymous> (C:\XXX\YYY\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
148202 verbose stack     at emitTwo (events.js:87:13)
148202 verbose stack     at EventEmitter.emit (events.js:172:7)
148202 verbose stack     at ChildProcess.<anonymous> (C:\XXX\YYY\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
148202 verbose stack     at emitTwo (events.js:87:13)
148202 verbose stack     at ChildProcess.emit (events.js:172:7)
148202 verbose stack     at maybeClose (internal/child_process.js:829:16)
148202 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
148203 verbose pkgid sp-pnp-js@1.0.4
148204 verbose cwd C:\XXX\YYY\OneDrive\Documents\SPFx\Projects\SiteInfo-webpart
148205 error Windows_NT 10.0.14915
148206 error argv "C:\Program Files\nodejs\node.exe" "C:\XXX\YYY\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
148207 error node v4.5.0
148208 error npm  v3.10.7
148209 error code ELIFECYCLE
148210 error sp-pnp-js@1.0.4 postinstall: `typings install`
148210 error Exit status 1
148211 error Failed at the sp-pnp-js@1.0.4 postinstall script 'typings install'.
148211 error Make sure you have the latest version of node.js and npm installed.
148211 error If you do, this is most likely a problem with the sp-pnp-js package,
148211 error not with npm itself.
148211 error Tell the author that this fails on your system:
148211 error     typings install
148211 error You can get information on how to open an issue for this project with:
148211 error     npm bugs sp-pnp-js
148211 error Or if that isn't available, you can get their info via:
148211 error     npm owner ls sp-pnp-js
148211 error There is likely additional logging output above.
148212 verbose exit [ 1, true ]

Regards

Nigel

**Comment by NPrice99** [comment]
Hi

 I finally got this to work by doing the following :-

 npm install typings -g

 which fixed the first problem and the I got "cannot find module 'sp-pnp-js'@ error

 I tried npm install -g sp-pnp-js --save

 That did not work.

 But npm install --save sp-pnp-js did work !!

 Regards

 Nigel
